### ISSUE TITLE
Can you help me understand why I'm getting different results w/ your package vs an online CRC calculator?

### ISSUE THREAD

**Issue by adamontherun** [nullfx/swift-nullfx.crc#10]
Hi,
I'm working on a BLE project where I have to calculate a CRC-8 value.

I have a working example in my Swift app where I have the values [0xAA, 0x14, 0xEB, 0x00, 0x00, 0x00, 0x00] and according to https://crccalc.com/?crc=0xAA 0x14 0xEB 0x00 0x00 0x00 0x00&method=crc8&datatype=hex&outtype=hex the check sum is OxC6

This works in my app as well so I believe its correct. 

When I use your library like this:
let val = Crc8.computeChecksum(on: [0xAA, 0x14, 0xEB, 0x00, 0x00, 0x00, 0x00])
var st = String(format:"%02X", val)
st += " is the hexadecimal representation of \(val)"
print(st)

I get a value of 75, which in Hex is 4B

Can you please help me understand what I'm doing wrong?

thanks!!
adam

**Comment by nullfx** [comment]
On your website you're looking at the wrong checksum.  the implementation here is the `CRC-8/DVB-S2` (using `x^8 + x^7 + x^6 + x^4 + x^2 + 1` poly) which shows the value of 0x4b as the CRC, the one it looks like you need is CRC CCITT.

if you look at the following table https://en.wikipedia.org/wiki/Cyclic_redundancy_check#Polynomial_representations_of_cyclic_redundancy_checks, the first `CRC-8` shown in the table from the website you've provided (with the `0xC6` result for the value) is actually the CRC-8 CCITT algorithm as it uses a polynomial of `0x07` (`x^8 + x2 + x + 1`) and not `0xD5` (`x^8 + x^7 + x^6 + x^4 + x^2 + 1`) as standard CRC-8 uses.
